In [1]:
import numpy as np
x = np.arange(10, 20)

y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])


In [2]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
y

array([ 2,  1,  4,  5,  8, 12, 18, 25, 96, 48])

In [4]:
r = np.corrcoef(x,y)

In [5]:
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

In [6]:
r[0,1]

0.7586402890911867

In [7]:
r[1,0]

0.7586402890911869

In [8]:
import numpy as np
import scipy.stats
x = np.arange(10, 20)
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [9]:
scipy.stats.pearsonr(x, y)

PearsonRResult(statistic=0.7586402890911869, pvalue=0.010964341301680853)

In [10]:
scipy.stats.spearmanr(x, y)

SignificanceResult(statistic=0.9757575757575757, pvalue=1.4675461874042197e-06)

In [11]:
scipy.stats.kendalltau(x, y)

SignificanceResult(statistic=0.911111111111111, pvalue=2.9761904761904762e-05)

In [12]:
scipy.stats.spearmanr(x, y).correlation 

0.9757575757575757

In [13]:
scipy.stats.kendalltau(x, y).correlation

0.911111111111111

In [14]:
r, p = scipy.stats.pearsonr(x, y)

In [15]:
r

0.7586402890911869

In [16]:
p

0.010964341301680853

In [17]:
import pandas as pd
x = pd.Series(range(10, 20))

In [18]:
x

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [19]:
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [20]:
y

0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64

In [21]:
x.corr(y)

0.7586402890911867

In [22]:
y.corr(x)

0.7586402890911869